// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBz8Pexj_OqpBkgc3mB9Wn0sh25-NDw8',
    appId: '1:1010679459602:web:6cba2023488af439728dcb',
    messagingSenderId: '1010679459602',
    projectId: 'scamtap-d924c',
    authDomain: 'scamtap-d924c.firebaseapp.com',
    storageBucket: 'scamtap-d924c.firebasestorage.app',
    measurementId: 'G-N309QJY04L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx08uh2rlj4Ed6GzF6MLaY-VqbGkoYK94',
    appId: '1:1010679459602:android:ab43ee9e47f8312d728dcb',
    messagingSenderId: '1010679459602',
    projectId: 'scamtap-d924c',
    storageBucket: 'scamtap-d924c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6cHrduhBN0rf7UTBzG-sDiEKmzMqBhyM',
    appId: '1:1010679459602:ios:903bb112ae23cbf2728dcb',
    messagingSenderId: '1010679459602',
    projectId: 'scamtap-d924c',
    storageBucket: 'scamtap-d924c.firebasestorage.app',
    iosBundleId: 'com.example.scamTap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6cHrduhBN0rf7UTBzG-sDiEKmzMqBhyM',
    appId: '1:1010679459602:ios:903bb112ae23cbf2728dcb',
    messagingSenderId: '1010679459602',
    projectId: 'scamtap-d924c',
    storageBucket: 'scamtap-d924c.firebasestorage.app',
    iosBundleId: 'com.example.scamTap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrBz8Pexj_OqpBkgc3mB9Wn0sh25-NDw8',
    appId: '1:1010679459602:web:99390a88db95030a728dcb',
    messagingSenderId: '1010679459602',
    projectId: 'scamtap-d924c',
    authDomain: 'scamtap-d924c.firebaseapp.com',
    storageBucket: 'scamtap-d924c.firebasestorage.app',
    measurementId: 'G-3RVZFKECSF',
  );
}
